### ISSUE TITLE
kotlin版本太低导致用不了

### ISSUE THREAD

**Issue by WiiliamChik** [bytedance/AabResGuard#18]
信息如下，望解决，十分感谢哈

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
root project 'color_app' -> com.bytedance.android:aabresguard-plugin:0.1.3 -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0

**Comment by JingYeoh** [comment]
@WiiliamChik 请给出 `AGP(com.android.tools.build:gradle:)` 和 `Gradle` 版本。

或者请尝试一下在根目录 `build.gradle` 文件中，`aabresguard` 在 `kotlin plugin` 之前引入。

```
classpath "com.bytedance.android:aabresguard-plugin:0.1.3"
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.10"
```

**Comment by WiiliamChik** [comment]
@JingYeoh 
classpath 'com.android.tools.build:gradle:3.5.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by JingYeoh** [comment]
@WiiliamChik 
请在工程中引入 `kotlin-plugin 1.3.10` 版本

```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.10"
```
