### ISSUE TITLE
说明文档中，过滤掉/arm64-v8a/，导致googleplayer审核不过

### ISSUE THREAD

**Issue by xyz-fly** [bytedance/AabResGuard#19]
默认配置说明中这段：

    filterList = [ // file filter rules
        "*/arm64-v8a/*",
        "META-INF/*"
    ]

这段应该把   "*/arm64-v8a/*", 去掉，否则会导致生成aab无法在 google player 审核通过 ---- 原因是缺少对64位支持

**Comment by JingYeoh** [comment]
@xyz-fly `filterList ` 是给特殊场景使用的，建议上传 GP 的包使用 `enableFilterFiles=false` 配置。

**特殊场景：** 比如某些渠道需要通过 aab 生成全量 apk 包给用户测试，但是同时包含 32/64 位的 so 会导致 apk 太大，所以可以使用该配置，过滤 64 位 so 只生成 32 位 apk。

AabResGuard  在 `core` 中也提供了相应功能支持的类，如果需要定制 `gradle task` 对 aab 进行修改的话，也可以通过引入 `aabresguard-core` 来快速达到目标。
