### ISSUE TITLE
how  to  remove mapping.txt from .aab/bundle

### ISSUE THREAD

**Issue by trycatchx** [bytedance/AabResGuard#20]
如何移除 aab 中的 mapping.txt ，并不想把映射关系提供出去。是否可行？或者有所影响？如何实施。

**Comment by JingYeoh** [comment]
@zhangchaojiong 你是指 `BUNDLE_METADATA/{package}/proguard.map` 文件？这个文件应该是用于 `Google play crash stack traces` 的。

具体可参考：[Deobfuscate crash stack traces
](https://support.google.com/googleplay/android-developer/answer/6295281?hl=en)

**Comment by JingYeoh** [comment]
@zhangchaojiong 如果仍需要过滤该文件的话，请使用`aabresguard-plugin:0.1.4:`及以上版本，并使用如下配置：

```
enableFilterFiles = true
filterList = [
        "BUNDLE-METADATA/**/proguard.map"
]
```

**Comment by trycatchx** [comment]
@JingYeoh 如果不把 `proguard.map` 加入白名单中（`filterList `），这个文件（`proguard.map`）内容也会被混淆，也会被影响到 bug 的追踪吧。我的问题清楚了，谢谢@JingYeoh

**Comment by JingYeoh** [comment]
@zhangchaojiong 资源混淆只影响资源目录下的文件，即 `*/res/*` ，其他目录下的文件不会受到影响。

**Comment by trycatchx** [comment]
@JingYeoh 那加入下面这个白名单的意义是？不打包到bundle 里面去？
```
filterList = [
        "BUNDLE-METADATA/**/proguard.map"
]
```

**Comment by JingYeoh** [comment]
@zhangchaojiong 这不是白名单，这是需要过滤的文件，详情请参考 [Wiki](https://github.com/bytedance/AabResGuard/blob/develop/wiki/zh-cn/README.md#gradle-plugin)

当`enableFilterFiles =true`时，在最终生成的混淆包中过滤掉符合`filterList` 规则的文件。

**Comment by trycatchx** [comment]
嗯嗯，那我知道了。符合 `whiteList `规则的文件是不参与混淆，符合 `filterList`  规则的文件不打包进 `.aab`。
