### ISSUE TITLE
混淆功能开关

### ISSUE THREAD

**Issue by MrUncleX** [bytedance/AabResGuard#29]
resources-mapping
res entries path mapping
这两部分有混淆开关吗 不混淆该如何配置呢

**Comment by JingYeoh** [comment]
@MrUncleX 抱歉，暂时没有针对混淆单独设置开关，之后会添加上这个功能

**Comment by MrUncleX** [comment]
还有个问题想请教下 我使用proguard打算混淆activity或者自定义view
bundletool能修改androidManifest和相关xml吗
您是怎么学习并使用bundletool的呢 目前没找到bundletool相关文档

**Comment by MrUncleX** [comment]
您好 请教个问题 假如我使用了proguard混淆了自定义view bundletool有什么方式可以去修改相应xml内容吗 
感谢您的回复

**Comment by JingYeoh** [comment]
@MrUncleX 自定义 view 不可以混淆，这不属于资源混淆的一部分，更加偏向代码混淆，bundletool 本身不处理这块的逻辑。

**Comment by JingYeoh** [comment]
@MrUncleX 0.1.5 版本添加了混淆开关，请使用 0.1.5 版本，并在 aabresguard plugin 中使用 `enableObfuscate` 参数来控制是否需要混淆
