### ISSUE TITLE
AGP-3.4.1

### ISSUE THREAD

**Issue by wtfisthatzzz** [bytedance/AabResGuard#4]
Unable to load class 'com.android.build.gradle.internal.tasks.BundleTask'.

**Comment by wtfisthatzzz** [comment]
AS版本3.5.2，gradle插件版本3.4.1

**Comment by wtfisthatzzz** [comment]
把sample的gradle插件版本修改为3.4.1也是报这个错

**Comment by JingYeoh** [comment]
@liuke2016 抱歉，AabResGuard 当是是基于 3.2.1 进行研发的，3.4.1 版本把 `com.android.build.gradle.internal.tasks.BundleTask` 改名为了 `'com.android.build.gradle.internal.tasks.PackageBundleTask'` 。

我会尽快进行兼容。

**Comment by JingYeoh** [comment]
@liuke2016 感谢反馈，问题已修复，请使用 `0.1.1` 版本进行重新尝试。
