### ISSUE TITLE
使用 plugin 插件打 aab 包 直接报以下错误

### ISSUE THREAD

**Issue by tao111222333444** [bytedance/AabResGuard#50]
使用 plugin 插件打 aab 包 直接报以下错误
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:aabresguardFlavorRleaseRelease'.
> Unexpected resource dir:     java.util.Iterator $load$44227() -> a

**Info (please complete the following information):**
 - AabResGuard  version [e.g. 0.1.8]
 - Android studio version: [e.g. Android Studio 4.1.2] 
 - AGP version: [e.g. com.android.tools.build:bundletool:3.2.1]
 - Gradle version: [e.g. gradle-6.1.1]

**Comment by JingYeoh** [comment]
@tao111222333444 辛苦提供下 AGP 版本和 Gradle 版本

**Comment by tao111222333444** [comment]
com.android.tools.build:gradle:4.1.2

**Comment by tao111222333444** [comment]
https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by tao111222333444** [comment]
应该是混淆的时候报错的

**Comment by tao111222333444** [comment]
# compiler: R8
# compiler_version: 2.1.86
# min_api: 21
# pg_map_id: 83236b6
# common_typos_disable
$$ServiceLoaderMethods -> a:
    java.util.Iterator $load$44227() -> a
    java.util.Iterator $load$77797() -> b

**Comment by tao111222333444** [comment]
这个是我混淆的映射文件（mapping）开头的位置  这个错误直接指向这个地方

**Comment by tao111222333444** [comment]
@JingYeoh

**Comment by JingYeoh** [comment]
@tao111222333444 辛苦使用 `0.1.9` 版本试试，使用相同的 gradle 和 AGP 没有复现这个问题

**Comment by zuoyuan333** [comment]
[BT:0.9.0] Error: Unexpected resource dir:     int compare(int,int) -> OooO00o
java.lang.IllegalArgumentException: Unexpected resource dir:     int compare(int,int) -> OooO00o
        at com.bytedance.android.aabresguard.parser.ResourcesMappingParser.parse(ResourcesMappingParser.java:45)
        at com.bytedance.android.aabresguard.executors.ResourcesObfuscator.<init>(ResourcesObfuscator.java:66)
        at com.bytedance.android.aabresguard.commands.ObfuscateBundleCommand.execute(ObfuscateBundleCommand.java:217)
        at com.bytedance.android.aabresguard.AabResGuardMain.main(AabResGuardMain.java:51)
        at com.bytedance.android.aabresguard.AabResGuardMain.main(AabResGuardMain.java:26)

**Comment by zuoyuan333** [comment]
0.1.9版本也有这个问题

**Comment by zuoyuan333** [comment]
@tao111222333444  遇到了同样的问题，你解决这个问题了吗

**Comment by tao111222333444** [comment]
换了个项目就可以了

**Comment by pol2edo** [comment]
最后怎么解决啊？适用如下配置一样会报mapping的错误
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
classpath "com.android.tools.build:gradle:7.0.2"
插件版本是这个：
 classpath "com.bytedance.android:aabresguard-plugin:0.1.10"

**Comment by pol2edo** [comment]
> 换了个项目就可以了

最后怎么解决啊？适用如下配置一样会报mapping的错误
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
classpath "com.android.tools.build:gradle:7.0.2"
插件版本是这个：
 classpath "com.bytedance.android:aabresguard-plugin:0.1.10"

**Comment by pol2edo** [comment]
> @tao111222333444 辛苦使用 `0.1.9` 版本试试，使用相同的 gradle 和 AGP 没有复现这个问题

最后怎么解决啊？适用如下配置一样会报mapping的错误
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
classpath "com.android.tools.build:gradle:7.0.2"
插件版本是这个：
 classpath "com.bytedance.android:aabresguard-plugin:0.1.10"
